apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: t6x0y1ahi-python
  janus-idp.io/tekton: t6x0y1ahi-python
  backstage.io/kubernetes-id: t6x0y1ahi-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: t6x0y1ahi-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
